### ISSUE TITLE
QUOTA_BYTES_PER_ITEM quota exceeded

### ISSUE THREAD

**Issue by helciodasilva** [edoreld/mark-as-read#5]
This error comes when you use chrome.storage.sync.set...to set the data greater than 8,192 bytes for a single item as chrome.storage.sync.set allows 8,192 QUOTA_BYTES_PER_ITEM.

You can use chrome.storage.local.set, to save the large data...instead of chrome.storage.sync.set.
````diff
-chrome.storage.sync
+chrome.storage.local
````
You can set the permission as unlimitedStorage in manifest.json file.
````diff
-"permissions": ["activeTab", "tabs", "storage", "downloads", "http://*/", "https://*/"],
+"permissions": ["activeTab", "tabs", "storage", "downloads", "http://*/", "https://*/", "unlimitedStorage"],
````

**Comment by edoreld** [comment]
Thanks for the feedback. Since the functionality to import and export has been recently (and conveniently!) added, it seems like we can do this change now. 

Would you like to do a PR since you already know where to do the changes?
